"""Installer config packaging — T4-02.

Produces a YAML config file that a customer-side Sentry agent can
consume verbatim (`/etc/sentry-agent/config.yaml`) and packages it
behind a signed, time-limited URL.

Design
------
- The URL is the credential. A 24-hour TTL is enforced by a signed
  payload, the same pattern as S3 pre-signed URLs.
- The raw API key is embedded in the signed payload, not stored
  server-side — no Redis / DB state, no cleanup cron.
- Rotation happens at URL *issuance* time (inside the authenticated
  POST handler). The 24h overlap window from T1-06 keeps previously
  deployed agents working until they pull the new config.
- Signature is HMAC-SHA256 over the base64url-encoded payload with
  `settings.SECRET_KEY`. `hmac.compare_digest` avoids timing oracles.

The token string layout is `<payload_b64url>.<sig_b64url>`, mirroring
JWS compact serialization but without JWT's claim-name overhead.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Any

INSTALLER_TOKEN_TTL = timedelta(hours=24)

# Embedded in the signed payload so a future key rotation can
# invalidate old tokens without changing the secret itself. Bump this
# when the payload schema changes incompatibly.
TOKEN_VERSION = 1


class InstallerTokenError(ValueError):
    """Raised on any token-verification failure.

    We intentionally do NOT distinguish expired / tampered / malformed
    at the API surface — callers translate this to a generic 410 Gone
    so attackers cannot use error messages to probe the token format.
    """


@dataclass(frozen=True)
class InstallerTokenPayload:
    tenant_id: str
    api_key: str
    server_url: str
    expires_at: datetime
    version: int = TOKEN_VERSION

    def to_dict(self) -> dict[str, Any]:
        return {
            "v": self.version,
            "t": self.tenant_id,
            "k": self.api_key,
            "s": self.server_url,
            "e": int(self.expires_at.timestamp()),
        }

    @classmethod
    def from_dict(cls, raw: dict[str, Any]) -> InstallerTokenPayload:
        required = ("v", "t", "k", "s", "e")
        for key in required:
            if key not in raw:
                raise InstallerTokenError(f"missing field: {key}")
        return cls(
            tenant_id=str(raw["t"]),
            api_key=str(raw["k"]),
            server_url=str(raw["s"]),
            expires_at=datetime.fromtimestamp(int(raw["e"]), tz=UTC),
            version=int(raw["v"]),
        )


# ---------------------------------------------------------------------------
# YAML builder
# ---------------------------------------------------------------------------

def build_config_yaml(
    *,
    tenant_id: str,
    api_key: str,
    server_url: str,
    heartbeat_interval_s: int = 60,
) -> str:
    """Render the agent-side `config.yaml`.

    Hand-rendered (no PyYAML dep) because the shape is fixed and the
    four scalar fields all have safe character sets — UUIDs, the
    `sk_live_*` alphabet, HTTPS URLs, integers. If the schema ever
    grows nested maps, switch to PyYAML.
    """
    # Basic safety: refuse embedded newlines / double-quotes in the
    # url so we can't get tricked into injecting YAML syntax.
    for name, value in ("server_url", server_url), ("tenant_id", tenant_id), (
        "api_key", api_key,
    ):
        if "\n" in value or '"' in value:
            raise ValueError(f"{name} contains illegal character")

    return (
        "# Generated by Sentry — do not edit manually.\n"
        "# Rotating this key: POST /api/v1/installer/config\n"
        "\n"
        f'server_url: "{server_url.rstrip("/")}"\n'
        f'tenant_id: "{tenant_id}"\n'
        f'api_key: "{api_key}"\n'
        f"heartbeat_interval_s: {int(heartbeat_interval_s)}\n"
    )


# ---------------------------------------------------------------------------
# Signed token — sign / verify
# ---------------------------------------------------------------------------

def _b64url_encode(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def _b64url_decode(value: str) -> bytes:
    # Re-pad so the stdlib decoder accepts rstripped urlsafe tokens.
    pad = "=" * (-len(value) % 4)
    try:
        return base64.urlsafe_b64decode(value + pad)
    except (ValueError, TypeError) as exc:
        raise InstallerTokenError("malformed base64") from exc


def _sign(payload_b64: str, secret: str) -> str:
    mac = hmac.new(
        secret.encode("utf-8"),
        payload_b64.encode("ascii"),
        hashlib.sha256,
    )
    return _b64url_encode(mac.digest())


def sign_download_token(payload: InstallerTokenPayload, secret: str) -> str:
    """Produce `<payload>.<sig>` over the UTF-8 JSON payload.

    Ordering via sort_keys so two encodes of the same payload match
    byte-for-byte — useful in tests and when verifying replays.
    """
    payload_json = json.dumps(
        payload.to_dict(), sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    payload_b64 = _b64url_encode(payload_json)
    signature_b64 = _sign(payload_b64, secret)
    return f"{payload_b64}.{signature_b64}"


def verify_download_token(
    token: str,
    *,
    secret: str,
    now: datetime | None = None,
) -> InstallerTokenPayload:
    """Validate signature, version, and expiry. Returns payload.

    Raises `InstallerTokenError` on any failure — the handler should
    surface a single 410 status regardless of which check failed.
    """
    if not isinstance(token, str) or token.count(".") != 1:
        raise InstallerTokenError("token shape")

    payload_b64, signature_b64 = token.split(".", 1)
    expected_sig = _sign(payload_b64, secret)
    if not hmac.compare_digest(expected_sig, signature_b64):
        raise InstallerTokenError("signature mismatch")

    try:
        raw_payload = json.loads(_b64url_decode(payload_b64).decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise InstallerTokenError("payload decode") from exc
    if not isinstance(raw_payload, dict):
        raise InstallerTokenError("payload shape")

    payload = InstallerTokenPayload.from_dict(raw_payload)
    if payload.version != TOKEN_VERSION:
        raise InstallerTokenError("token version")

    now = now or datetime.now(UTC)
    if payload.expires_at <= now:
        raise InstallerTokenError("token expired")

    return payload


def build_download_url(*, base_url: str, token: str) -> str:
    """Assemble the agent-facing download URL.

    `base_url` is the public API origin — e.g. `https://api.sentry.mn`.
    We do NOT url-encode the token: it is already base64url-safe so
    `.` is the only non-alphanumeric character, and that's a valid
    URL path segment.
    """
    origin = base_url.rstrip("/") if base_url else ""
    return f"{origin}/api/v1/installer/config/{token}"


def issue_installer_token(
    *,
    tenant_id: str,
    api_key: str,
    server_url: str,
    secret: str,
    now: datetime | None = None,
    ttl: timedelta = INSTALLER_TOKEN_TTL,
) -> tuple[str, datetime]:
    """Convenience wrapper — build the payload, sign, return token + exp."""
    now = now or datetime.now(UTC)
    expires_at = now + ttl
    payload = InstallerTokenPayload(
        tenant_id=tenant_id,
        api_key=api_key,
        server_url=server_url,
        expires_at=expires_at,
    )
    return sign_download_token(payload, secret), expires_at


__all__ = [
    "INSTALLER_TOKEN_TTL",
    "TOKEN_VERSION",
    "InstallerTokenError",
    "InstallerTokenPayload",
    "build_config_yaml",
    "build_download_url",
    "issue_installer_token",
    "sign_download_token",
    "verify_download_token",
]
